config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :categories do
    resources :images
  end
  resources :sub_images
  resources :inside_images
  resources :wood_elemnts

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :images
	mount_uploader :profile_image, PictureUploader
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :category
	has_many :sub_images, dependent: :destroy
	has_one :inside_image, dependent: :destroy
	has_many :wood_elemnts, dependent: :destroy
	accepts_nested_attributes_for :sub_images
	mount_uploader :photo, PictureUploader
end

app/models/inside_image.rb
class InsideImage < ActiveRecord::Base
	belongs_to :image
end

app/models/sub_image.rb
class SubImage < ActiveRecord::Base
	belongs_to :image
	mount_uploader :small_image, PictureUploader
end

app/models/wood_elemnt.rb
class WoodElemnt < ActiveRecord::Base
	belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index

	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to category_path(@category)
		else
			render 'new'
		end
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to root_path

	end

	private

	def category_params
		params.require(:category).permit(:name, :description, :profile_image)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_category
	def index
		@images = @category.images
	end

	def new
		@image = @category.images.build
		@sub_images = @image.sub_images.build
	end

	def create
		@image = @category.images.build(image_params)
		if @image.save
			redirect_to category_path(@category)
		else
			render 'new'
		end
	end

	def edit
		@image = @category.images.find(params[:id])
		@sub_images = @image.sub_images
	end

	def update
		@image = @category.images.find(params[:id])
		if @image.update(image_params)
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def show
		@image = @category.images.find(params[:id])
	end

	def destroy
		@image = @category.images.find(params[:id])
		@image.destroy
		respond_to do |format|
      format.html { redirect_to category_path(@category) }
      format.js
    end
	end

	private
	def set_category
		@category = Category.find(params[:category_id])
	end

	def image_params
		params.require(:image).permit(:photo, :i_name, :i_bio, :price, sub_images_attributes: [:image_id, :small_image])
	end
end

app/controllers/inside_images_controller.rb
class InsideImagesController < ApplicationController
	before_action :set_image

	def new
		@inside_image = @image.inside_image.build
	end

	def create
		@inside_image = @image.inside_image.build(inside_image_params)
		if @inside_image.save
			redirect_to category_image_path(@image.category, @image)
		else
			render 'new'
		end
	end 

	def edit
		@inside_image = @image.inside_image
	end

	def update
		@inside_image = @image.inside_image
		if @inside_image.update(inside_image_params)
			redirect_to category_image_path(@image.category, @image)
		else
			render 'edit'
		end
	end

	def show
		@inside_image = @image.inside_image
	end

	def destroy
		@inside_image = @image.inside_image
		@inside_image.destroy
		redirect_to category_image_path(@image.category, @image)
	end

	private

	def set_image
		@image = Image.find(params[:id])
	end

	def inside_image_params
		params.require(:inside_image).permit(:picture, :description)
	end

end

app/controllers/sub_images_controller.rb
class SubImagesController < ApplicationController
	before_action :set_image, except: [:new]

	def index

	end



	def edit
		@sub_image = @image.sub_images.find(params[:id])
	end

	def update
		sub_image = @image.sub_images.find(params[:id])
		if sub_image.update(sub_params)
			redirect_to :back
		else
			render 'edit'
		end
	end

	def show
		@sub_image = @image.sub_images.find(params[:id])
	end

	def destroy
		@sub_image = @image.sub_images.find(params[:id])
		@sub_image.destroy
		redirect_to :back
	end

	private

	def set_image
		@image = Image.find(params[:id])
	end

	def sub_params
		params.require(:sub_image).permit(:small_image)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home

	end
end

app/controllers/wood_elemnts_controller.rb
class WoodElemntsController < ApplicationController
	before_action :set_image

	def new
		@wood_elemnt = @image.wood_elemnts.build
	end

	def create
		@wood_elemnt = @image.wood_elemnts.build(wood_params)
		if @wood_elemnt.save
			redirect_to category_image_path(@image.category, @image)
		else
			render 'new'
		end
	end 

	def edit
		@wood_elemnt = @image.wood_elemnts.find(params[:id])
	end

	def update
		@wood_elemnt = @image.wood_elemnts.find(params[:id])
		if @wood_elemnt.update(wood_params)
			redirect_to category_image_path(@image.category, @image)
		else
			render 'edit'
	end

	def show
		@wood_elemnt = @image.wood_elemnts.find(params[:id])
	end

	def destroy
		@wood_elemnt = @image.wood_elemnts.find(params[:id])
		@wood_elemnt.destroy
		redirect_to

	end

	private

	def set_image
		@image = Image.find(params[:id])
	end

	def wood_params
		params.require(:wood_elemnt).permit(:pic, :number)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inside_images_helper.rb
module InsideImagesHelper
end

app/helpers/sub_images_helper.rb
module SubImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wood_elemnts_helper.rb
module WoodElemntsHelper
end

app/views/categories/_form.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well well-f">
			<%= form_for @category do |f| %>
				<div class="form-group">
					<%= f.label :profile_image %>
			    <%= f.file_field :profile_image, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
		    </div>
				<div class="form-group">
					<%= f.label :name %><br/>
					<%= f.text_field :name, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :description %><br/>
					<%= f.text_area :description, rows: 6, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.submit class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
</div>




	

app/views/categories/_images.html.erb
<% @category.images.each do |image| %>
	<div class="col-md-6"  id= "panel_<%= image.id %>" >
		
			<div class="panel panel-default panel-show">
				<div class="panel-body panel-body-show">
					<%= image_tag(image.photo.url(:thumb), class: "img-in img-responsive") %>
					<%= link_to "delete", category_image_path(@category, image), remote: true, method: :delete, data: {confirm: "Are you sure?"} %> 					  <%= link_to "edit", edit_category_image_path(@category, image) %>
					<ul class="imgs-tables">	
						<li><h2><%= image.i_name %></h2></li>
						<hr class="for-title">
						<li class="second-one"><p><%= image.i_bio %></p></li>
						<% if image.price %>
							<li class="price-title"><h3> Price: </h3> </li> <li class="price-li"><h4 class="for-price"><%= image.price %><i class="fa fa-ils"></i></h4></li><br/>
							<hr class="price-line-up">
							<hr class="price-line-down">
						<% end %>
					</ul>
				<ul class="sub-images-show">	
					<% image.sub_images.each do |sub_image| %>
						<li><%= image_tag(sub_image.small_image.url(:small))  %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
	<div class="col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/new.html.erb
<div class="row">
	<div class="col-md-offset-4">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="row">
	<div class="col-md-12 text-center">
		<div class="well well-coll">
			<ul class="category-show-p">
				<li><h1><%= @category.name %></h1></li>
				<li><%= image_tag(@category.profile_image.url, class: "img-thumbnail") %></li><br/>
				<li><p><%= @category.description %></p></li>
			</ul>	
				<div class="col-md-10 col-md-offset-1">
					<div class="jumbotron jumbotron-category">

					</div>
					<div class="btn-category-s"><%= link_to "Upload New Image", new_category_image_path(@category), class: "btn btn-lg btn-success"%></div>
					<% @category.images.each do |image| %>
						<div class="col-md-6" id= "panel_<%= image.id %>">
							
								<div class="panel panel-default panel-show">
									<div class="panel-body panel-body-show">
										<%= link_to image_tag(image.photo.url(:thumb), class: "img-in img-responsive img-rounded"), category_image_path(@category, image) %>
										<%= link_to "delete", category_image_path(@category, image), method: :delete, data: {confirm: "Are you sure?"}, remote: true %> 					  <%= link_to "edit", edit_category_image_path(@category, image) %>
										<ul class="imgs-tables">	
											<li><h2><%= image.i_name %></h2></li>
											<hr class="for-title">
											<li class="second-one"><p><%= image.i_bio %></p></li>
											<% if image.price %>
												<li class="price-title"><h3> Price: </h3> </li> <li class="price-li"><h4 class="for-price"><%= image.price %><i class="fa fa-ils"></i></h4></li><br/>
												<hr class="price-line-up">
												<hr class="price-line-down">
											<% end %>
										</ul>
									<ul class="sub-images-show">	
										<% image.sub_images.each do |sub_image| %>
											<li><%= image_tag(sub_image.small_image.url(:small))  %></li>
										<% end %>
									</ul>
								</div>
							</div>
						</div>
					<% end %>
				</div>
		</div>
	</div>
</div>

app/views/images/_form.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well well-f">
			<%= form_for [@image.category, @image], multiple: true do |f| %>
		    <div class="form-group">
					<%= f.label :photo %>
			    <%= f.file_field :photo, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
		    </div>
				<div class="form-group">
					<%= f.label :Name %>
			    <%= f.text_field :i_name, class: 'form-inline' %>
			    
					<%= f.label :Price %>
			    <%= f.text_field :price, class: 'form-inline ' %>
		    </div>
		    <div class="form-group">
					<%= f.label :Description %>
			    <%= f.text_area :i_bio, rows: 5, class: 'form-control' %>
		    </div>
		    <div class="form-group">
		    	<%= f.fields_for :sub_images, @sub_images do |builder| %>
						<%= builder.label :small_image %>
				    <%= builder.file_field :small_image, accept: 'image/jpeg,image/gif,image/png,image/jpg', multiple: true, name: "image[sub_images_attributes][][small_image]", id: "upload-image" %>
			    <% end %>
		    </div>
				<div class="form-group">
					<%= f.submit class: 'btn btn-primary' %>
				</div>
			<% end %>
			<script id="template-upload" type="text/x-tmpl">
			<div class="upload">
				{%=o.name%}
				<div class="progress"><div class="bar" style="width: 0%"></div></div>
			</div>
			</script>
		</div>
	</div>
</div>




	

app/views/images/destroy.js.erb
$('#panel_<%= @image.id %>').remove();

app/views/images/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/images/new.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-2">
		<%= render 'form' %>
	</div>
</div>

app/views/images/show.html.erb
<ul>
	<li><%= @image.i_name %></li>
	<li><%= link_to "Upload image", new_category_image_path(@category), class: "btn btn-lg btn-success"%></li>
</ul>

app/views/inside_images/_form2.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well well-f">

			<%= form_for @inside_image do |f| %>
				<div class="form-group">
						<%= f.label :picture %>
				    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
			  </div>
			  <div class="form-group">
					<%= f.label :Description %>
			    <%= f.text_area :description, rows: 5, class: 'form-control' %>
			  </div>
			<% end %>

		</div>
	</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-ma">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Wood Work</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WoodWork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= render 'layouts/navigation' %>
		<%= render 'layouts/messages' %>
<%= yield %>


</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h2 class="panel-title">
				<%= pluralize(obj.errors.count, "error") %>
				prohibited this post from being saved:
			</h2>
			<div class="panel-body">
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/sub_images/_form.html.erb
<div class="row">
	<div class="col-md-6">
		<%= render 'shared/errors', obj: @sub_image %>
		<div class="well well-f">
			<%= form_for @sub_image do |f| %>
				<div class="form-group">
					<%= f.label :small_image %>
			    <%= f.file_field :small_image, accept: 'image/jpeg,image/gif,image/png,image/jpg' %>
		    </div>
				<div class="form-group">
					<%= f.submit class: 'btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
</div>




	

app/views/sub_images/new.html.erb
<%= render 'form' %>

app/views/welcome/home.html.erb
<div id="width-r">
	<%= image_tag("wood1.jpg", class: "inside so-1 clipp")  %>
	<%= image_tag("wood2.jpg",class: "inside so-2 clippp" ) %>
	<%= image_tag("wood3.jpg", class: "inside so-3 clippp")  %>
	<%= image_tag("wood4.jpg", class: "inside so-4 clippp")  %>
	<%= image_tag("wood5.jpg", class: "inside so-5")  %>

</div>